modules/laboratory/controllers/ProcedureController.php
<?php

namespace modules\laboratory\controllers;

use common\models\classes\FormattingRecord;
use common\models\classes\FormattingSchedule;
use common\models\entity\Doctor;
use common\models\entity\HospitalSchedule;
use common\models\entity\Patient;
use common\models\entity\PatientCardHistory;
use common\models\entity\PreRecordsProcedures;
use common\models\entity\PreRecordsProceduresAttachments;
use common\models\entity\Procedure;
use common\models\entity\ScheduleRecordsDoctors;
use common\models\enums\ObjectTypesInPatientCard;
use common\models\enums\PreRecordsStatusTypes;
use common\models\enums\ProcedureVisitStatus;
use common\models\search\HospitalScheduleSearch;
use common\models\search\PatientSearch;
use common\models\search\PreRecordsProceduresSearch;
use common\models\search\ProcedureSearch;
use DateTime;
use modules\doctorprofile\models\classes\DoctorRecords;
use modules\laboratory\models\classes\SaveProcedure;
use modules\laboratory\models\forms\EditPreRecordProcedureForm;
use Symfony\Component\String\Inflector\FrenchInflector;
use Yii;
use yii\base\InvalidArgumentException;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * HospitalScheduleController implements the CRUD actions for HospitalSchedule model.
 */
class ProcedureController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::class,
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                'access' => [
                    'class' => AccessControl::class,
                    'rules' => [
                        [
                            'actions' => ['index','update','add-record-to-patient-history','add-attachment','delete-attachment'],
                            'allow' => true,
                            'roles' => ['laboratoryʼs-records'],
                        ],
                    ],
                ],
            ]
        );
    }

    public function actionIndex()
    {
        $this->changeStatusPreviousDayRecords();
        $searchModel = new PreRecordsProceduresSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'dataProvider'=>$dataProvider,
            'searchModel'=>$searchModel,
        ]);
    }

    private function changeStatusPreviousDayRecords(){
        $records=PreRecordsProcedures::find()->where(['<=','visit_date',strtotime(date('d.m.y 00:00'))])
            ->andWhere(['status'=>ProcedureVisitStatus::DIRECTED])->all();
        if($records){
            foreach ($records as $record){
                /* @var $record PreRecordsProcedures */
                $record->status=ProcedureVisitStatus::DECLINE;
                $record->save();
            }
        }
    }

    public function actionAddRecordToPatientHistory($record_id){
        $model=new PatientCardHistory();
        $record=ScheduleRecordsDoctors::find()->where(['id'=>$record_id])->one();
        if($record){
            $patient=Patient::find()->where(['user_id'=>$record->user_id])->one();
            $model->patient_id=$patient->id;
            $model->doctor_id=$record->doctor_id;
            $model->visit_date=$record->created_at;
        }
        if ($model->load($this->request->post())) {
            if($model->save()){
                return $this->render('successfully-added-record-to-patient-history');
            }
            else{
                echo '<br>';
                echo '<br>';
                echo '<br>';
                echo '<br>';
                echo '<br>';
                echo '<br>';
                var_dump($model->errors);
            }

        }
        return $this->render('add-record-to-patient-history',[
            'model'=>$model,
            'patient'=>$patient,
        ]);

    }

    /**
     * Updates an existing HospitalSchedule model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param $record_id
     * @return string|Response
     * @throws Exception|\yii\base\InvalidConfigException
     */
    public function actionUpdate($record_id)
    {
        $model=new EditPreRecordProcedureForm($record_id);
        if ($model->load(Yii::$app->request->post())) {
            if($model->status==ProcedureVisitStatus::PROCESSED){
                $this->createRecordInPatientCardHistory($model->patient->id,$model->visit_date,
                    ObjectTypesInPatientCard::LABORATORY_ASSISTANT,$model->laboratory_assistant_id,$model->description);
            }
            if($model->saveProcedure()){
                return $this->redirect('index');
            }
            else{
                throw new Exception('Помилка збереження');
            }
        }
        return $this->render('update', [
            'model'=>$model,
        ]);
    }

    public function createRecordInPatientCardHistory($patient_id,$visit_date,$object_type,$object_id,$description): bool
    {
        $model=new PatientCardHistory();
        $model->patient_id=$patient_id;
        $model->visit_date=strtotime($visit_date);
        $model->object_type=$object_type;
        $model->object_id=$object_id;
        $model->description=$description;
        if($model->save()){
            return true;
        }
        else{
            dump($model->errors);
            die();
            return false;
        }

    }

    /**
     * @throws Exception|InvalidArgumentException
     */
    public function actionAddAttachment($record_id){
        $model=new PreRecordsProceduresAttachments();
        if ($model->load(Yii::$app->request->post())) {
            if($model->saveAttachment($record_id)){
                return $this->redirect(['update','record_id'=>$record_id]);
            }
            else{
                throw new Exception('Помилка збереження');
            }
        }
        return $this->render('add-attachments',[
            'model'=>$model,
        ]);
    }

    public function actionDeleteAttachment($attachment_id,$record_id){
        $attachment=PreRecordsProceduresAttachments::findOne($attachment_id);
        if($attachment){
            $attachment->delete();
            return $this->redirect(['update',
                'record_id'=>$record_id,
            ]);
        }
        else{
            throw new  Exception('Такого вкладення не існує');
        }

    }

}

modules/laboratory/views/procedure/add-attachments.php
<?php use common\models\entity\PreRecordsProceduresAttachments;
use kartik\file\FileInput;
use yii\bootstrap\Html;
use yii\bootstrap4\ActiveForm;
/* @var $model PreRecordsProceduresAttachments */
?>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
<div class="card card-default">
    <div class="card card-body">
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'imageFile')->widget(FileInput::class,
                    [
                        'options' => ['accept' => 'image/*'],
                        'pluginOptions' => [
                            'initialPreview' => (!$model->file) ? false : $model->file,
                            'initialPreviewAsData' => true,
                            'showPreview' => true,
                            'showRemove' => false,
                            'showUpload' => false
                        ],
                    ]); ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'name')->textInput()?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= Html::submitButton(Yii::t('app', 'Зберегти'), ['class' => 'btn btn-success']) ?>
            </div>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

modules/laboratory/views/procedure/index.php
<?php

use common\models\entity\Doctor;
use common\models\entity\Patient;
use common\models\entity\PreRecordsProcedures;
use common\models\entity\ProcedureTypes;
use common\models\enums\ProcedureVisitStatus;
use kartik\file\FileInput;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
/* @var $model PreRecordsProcedures */
?>
<div class="procedure-form">


    <h1><?= Html::encode($this->title) ?></h1>


    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'patient_id',
                'format' => 'raw',
                'value' => function ($data) {
                    /* @var $data PreRecordsProcedures */
                    return isset($data->patient_id) ?
                        $data->patient->surname . ' ' . $data->patient->name . ' ' . $data->patient->parent_name :
                        'Такого пацієнта не існує';
                }
            ],
            [
                'attribute' => 'doctor_id',
                'format' => 'raw',
                'filter' => Doctor::getDoctorsList(),
                'value' => function ($data) {
                    /* @var $data PreRecordsProcedures */
                    return isset($data->doctor_id) ? $data->doctor->surname . ' ' . $data->doctor->name : 'Такого лікаря не існує';
                }
            ],
            [
                'attribute' => 'visit_date',
                'format' => ['datetime', 'php:d.m.Y'],
            ],
            [
                'attribute' => 'procedure_type_id',
                'format' => 'raw',
                'filter' => ProcedureTypes::getProcedureTypesById(),
                'value' => function ($data) {
                    /* @var $data PreRecordsProcedures */
                    return isset($data->procedure_type_id) ? $data->procedureType->name : 'Такого аналізу не існує';
                }
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'filter' => ProcedureVisitStatus::listData(),
                'value' => function ($data) {
                    /* @var PreRecordsProcedures $data */
                    return isset($data->status) ? ProcedureVisitStatus::getLabel($data->status) : 'Такого статусу не існує';
                }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'header' => 'Дії',
                'template' => '{update}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        if (in_array($model->status,[ProcedureVisitStatus::DIRECTED,ProcedureVisitStatus::IN_PROCESS])) {
                            return Html::a(
                                '<span class="btn btn-primary " aria-hidden="true">Редагувати</span>',
                                Url::to(['procedure/update','record_id'=>$key]));
                        } else {
                            return '';
                        }
                    }
                ]
            ],
        ],
    ]); ?>

</div>

modules/laboratory/views/procedure/update.php
<?php

use common\models\enums\ProcedureVisitStatus;
use kartik\file\FileInput;
use modules\laboratory\models\forms\EditPreRecordProcedureForm;
use yii\bootstrap\Html;
use yii\bootstrap4\Modal;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model EditPreRecordProcedureForm */
?>
<div class="procedure-form">


    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
    <div class="card card-default">
        <div class="card card-body">
            <div class="row">
                <div class="col-md-4">
                    <div style="margin-bottom: 10px">
                        <?= Html::a('Добавити вкладення', ['procedure/add-attachment', 'record_id' => $model->record_id], ['class' => 'btn btn-primary']) ?>
                    </div>
                    <div>
                        <strong>
                            Список вкладень
                        </strong>
                    </div>
                    <table class="table" style="margin-top: 10px">
                        <thead>
                        <tr>
                            <th>
                                Вкладення
                            </th>
                            <th>
                                Назва файлу
                            </th>
                            <th>
                                Дії
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($model->attachments as $item): ?>
                            <tr>
                                <td>
                                    <?=Html::img($item->file,['style'=>'max-height:50px'])?>
                                </td>
                                <td>
                                    <?=$item->name?>
                                </td>
                                <td>
                                    <?= Html::a('X',['procedure/delete-attachment','attachment_id'=>$item->id,'record_id'=>$model->record_id],
                                        ['class'=>'btn btn-danger'])?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>

                    </table>

                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6">
                            <?= $form->field($model, 'patientFullName')->textInput(['readOnly' => true]) ?>
                        </div>
                        <div class="col-md-6">
                            <?= $form->field($model, 'doctorFullName')->textInput(['readOnly' => true]) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?= $form->field($model, 'visit_date')->textInput(['readOnly' => true]) ?>
                        </div>
                        <div class="col-md-4">
                            <?= $form->field($model, 'status')->dropDownList([
                                ProcedureVisitStatus::IN_PROCESS => ProcedureVisitStatus::getLabel(ProcedureVisitStatus::IN_PROCESS),
                                ProcedureVisitStatus::PROCESSED => ProcedureVisitStatus::getLabel(ProcedureVisitStatus::PROCESSED),
                                ProcedureVisitStatus::DECLINE => ProcedureVisitStatus::getLabel(ProcedureVisitStatus::DECLINE),
                            ]) ?>
                        </div>
                        <div class="col-md-4">
                            <?= $form->field($model, 'procedure_type_id')->textInput(['readOnly' => true]) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'description')->textarea() ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= Html::submitButton(Yii::t('app', 'Зберегти'), ['class' => 'btn btn-success']) ?>
                </div>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>